{
  "openapi": "3.0.0",
  "info": {
    "title": "User API",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "users",
      "description": "Everything to do with users."
    },
    {
      "name": "categories",
      "description": "The categories of your expenses."
    },
    {
      "name": "expenses",
      "description": "Managing your expenses."
    }
  ],
  "paths": {
    "/users": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Get all users",
        "responses": {
          "200": {
            "description": "List of users",
            "content": {
              "application/json": {
                "example": [
                  {
                    "userid": 1,
                    "email": "user1@example.com",
                    "username": "user1"
                  },
                  {
                    "userid": 2,
                    "email": "user2@example.com",
                    "username": "user2"
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "users"
        ],
        "summary": "Create a new user",
        "requestBody": {
          "description": "User object",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "example": {
                "email": "user3@example.com",
                "username": "user3"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User created successfully",
            "content": {
              "application/json": {
                "example": {
                  "success": true
                }
              }
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "Get user by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User details",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "user": {
                    "userid": 1,
                    "email": "user1@example.com",
                    "username": "user1"
                  }
                }
              }
            }
          },
          "404": {
            "description": "User not found",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "user": null
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "users"
        ],
        "summary": "Update user by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "description": "Updated user object",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "example": {
                "email": "updated@example.com",
                "username": "updateduser"
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "User updated successfully",
            "content": {
              "application/json": {
                "example": {
                  "success": true
                }
              }
            }
          },
          "404": {
            "description": "User not found",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "User not found."
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "users"
        ],
        "summary": "Delete user by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User deleted successfully",
            "content": {
              "application/json": {
                "example": {
                  "success": true
                }
              }
            }
          },
          "404": {
            "description": "User not found",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "User not found."
                }
              }
            }
          }
        }
      }
    },
    "/categories": {
      "get": {
        "tags": [
          "categories"
        ],
        "summary": "Get all categories",
        "responses": {
          "200": {
            "description": "List of categories",
            "content": {
              "application/json": {
                "example": [
                  {
                    "categoryid": 1,
                    "name": "Entertainment"
                  },
                  {
                    "categoryid": 2,
                    "name": "Uitilities"
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "categories"
        ],
        "summary": "Create a new category",
        "requestBody": {
          "description": "Category object",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Category"
              },
              "example": {
                "name": "Travel"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Category created successfully",
            "content": {
              "application/json": {
                "example": {
                  "success": true
                }
              }
            }
          }
        }
      }
    },
    "/categories/{id}": {
      "get": {
        "tags": [
          "categories"
        ],
        "summary": "Get category by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Category details",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "category": {
                    "categoryid": 1,
                    "name": "Entertainment"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Category not found",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "Category not found",
                  "category": null
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "categories"
        ],
        "summary": "Update category by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "description": "Updated category object",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Category"
              },
              "example": {
                "name": "Groceries"
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "Category updated successfully",
            "content": {
              "application/json": {
                "example": {
                  "success": true
                }
              }
            }
          },
          "404": {
            "description": "Category not found",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "Category not found."
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "categories"
        ],
        "summary": "Delete category by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Category deleted successfully",
            "content": {
              "application/json": {
                "example": {
                  "success": true
                }
              }
            }
          },
          "404": {
            "description": "Category not found",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "Category not found."
                }
              }
            }
          }
        }
      }
    },
    "/expenses": {
      "get": {
        "tags": [
          "expenses"
        ],
        "summary": "Get all expenses",
        "responses": {
          "200": {
            "description": "List of expenses",
            "content": {
              "application/json": {
                "example": [
                  {
                    "expenseid": 1,
                    "name": "Milk",
                    "amount": 15,
                    "description": "Dairy Product",
                    "date": "2022-05-01 19:17:25",
                    "categoryid": 1,
                    "userid": 1
                  },
                  {
                    "expenseid": 2,
                    "name": "Milk",
                    "amount": 20,
                    "description": "Dairy Product",
                    "date": "2023-08-15 05:12:32",
                    "categoryid": 1,
                    "userid": 3
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "expenses"
        ],
        "summary": "Create a new expense",
        "requestBody": {
          "description": "Expense object",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Expense"
              },
              "example": {
                "expenseid": 1,
                "name": "Milk",
                "amount": 15,
                "description": "Dairy Product",
                "date": "2022-05-01 19:17:25",
                "categoryid": 1,
                "userid": 1
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Expense created successfully",
            "content": {
              "application/json": {
                "example": {
                  "success": true
                }
              }
            }
          }
        }
      }
    },
    "/expenses/{id}": {
      "get": {
        "tags": [
          "expenses"
        ],
        "summary": "Get expense by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Expense details",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "expense": {
                    "expenseid": 1,
                    "name": "Milk",
                    "amount": 15,
                    "description": "Dairy Product",
                    "date": "2022-05-01 19:17:25",
                    "categoryid": 1,
                    "userid": 1
                  }
                }
              }
            }
          },
          "404": {
            "description": "Expense not found",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "Expense not found",
                  "expense": null
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "expenses"
        ],
        "summary": "Update expense by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "description": "Updated expense object",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Expense"
              },
              "example": {
                "name": "Milk",
                "amount": 25,
                "description": "Dairy Product",
                "date": "2023-05-01 19:17:25",
                "categoryid": 1,
                "userid": 1
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "Expense updated successfully",
            "content": {
              "application/json": {
                "example": {
                  "success": true
                }
              }
            }
          },
          "404": {
            "description": "Expense not found",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "Expense not found."
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "expenses"
        ],
        "summary": "Delete expense by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Expense deleted successfully",
            "content": {
              "application/json": {
                "example": {
                  "success": true
                }
              }
            }
          },
          "404": {
            "description": "Expense not found",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "Expense not found."
                }
              }
            }
          }
        }
      }
    },
    "/expenses/user/{id}": {
      "get": {
        "tags": [
          "expenses"
        ],
        "summary": "Get all user's expense by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User expense details",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "expense": [
                    {
                      "expenseid": 1,
                      "name": "Milk",
                      "amount": 15,
                      "description": "Dairy Product",
                      "date": "2022-05-01 19:17:25",
                      "categoryid": 1,
                      "userid": 1
                    },
                    {
                      "expenseid": 9,
                      "name": "Electricity",
                      "amount": 2500,
                      "description": "Electricity",
                      "date": "2023-08-12 08:00:00",
                      "categoryid": 4,
                      "userid": 1
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/expenses/user/{id}/average": {
      "get": {
        "tags": [
          "expenses"
        ],
        "summary": "Get the average for all user's expense by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User expense details",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "expense": [
                    {
                      "categoryid": 1,
                      "amount": 1250
                    },
                    {
                      "categoryid": 2,
                      "amount": 900
                    },
                    {
                      "categoryid": 3,
                      "amount": 750
                    },
                    {
                      "categoryid": 9,
                      "amount": 5
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "User and/or Expenses not found",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "User and/or Expenses not found",
                  "expense": null
                }
              }
            }
          }
        }
      }
    },
    "/expenses/user/{id}/sum": {
      "get": {
        "tags": [
          "expenses"
        ],
        "summary": "Get the sum for all user's expense by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User expense details",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "expense": [
                    {
                      "categoryid": 1,
                      "amount": 9000
                    },
                    {
                      "categoryid": 2,
                      "amount": 1350
                    },
                    {
                      "categoryid": 3,
                      "amount": 1500
                    },
                    {
                      "categoryid": 9,
                      "amount": 5
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "User and/or Expenses not found",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "User and/or Expenses not found",
                  "expense": null
                }
              }
            }
          }
        }
      }
    },
    "/expenses/user/{id}/category/{catId}": {
      "get": {
        "tags": [
          "expenses"
        ],
        "summary": "Get all user's expense by category",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "catId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User expense details",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "expense": [
                    {
                      "expenseid": 1,
                      "name": "Milk",
                      "amount": 15,
                      "description": "Dairy Product",
                      "date": "2022-05-01 19:17:25",
                      "categoryid": 1,
                      "userid": 1
                    },
                    {
                      "expenseid": 8,
                      "name": "Lettuce",
                      "amount": 9,
                      "description": "Vegetable",
                      "date": "2023-09-12 09:30:25",
                      "categoryid": 1,
                      "userid": 1
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/expenses/user/{id}/category/{catId}/average": {
      "get": {
        "tags": [
          "expenses"
        ],
        "summary": "Get the average for all user's expense by category",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "catId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User expense details",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "expense": {
                    "categoryid": 1,
                    "amount": 1250
                  }
                }
              }
            }
          },
          "404": {
            "description": "User and/or Category not found",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "User and/or Category not found",
                  "expense": null
                }
              }
            }
          }
        }
      }
    },
    "/expenses/user/{id}/category/{catId}/sum": {
      "get": {
        "tags": [
          "expenses"
        ],
        "summary": "Get the sum for all user's expense by category",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "catId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User expense details",
            "content": {
              "application/json": {
                "example": {
                  "success": true,
                  "expense": {
                    "categoryid": 1,
                    "amount": 9000
                  }
                }
              }
            }
          },
          "404": {
            "description": "User and/or Category not found",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "message": "User and/or Category not found",
                  "expense": null
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "userid": {
            "type": "integer"
          },
          "email": {
            "type": "string"
          },
          "username": {
            "type": "string"
          }
        }
      },
      "Category": {
        "type": "object",
        "properties": {
          "categoryid": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "Expense": {
        "type": "object",
        "properties": {
          "expenseid": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string"
          },
          "amount": {
            "type": "integer",
            "format": "int32"
          },
          "description": {
            "type": "string"
          },
          "date": {
            "type": "string",
            "format": "date-time"
          },
          "categoryid": {
            "type": "integer",
            "format": "int32"
          },
          "userid": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "ApiResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "user/category/expense": {
            "type": "object"
          }
        }
      }
    }
  }
}